CHORUS-TRE/chorus-tre

- charts/kube-prometheus-stack/Chart.lock
- charts/kube-prometheus-stack/Chart.yaml
https://github.com/prometheus/prometheus/releases/tag/v2.54.0
> chore(charts): bump kube-prometheus-stack to 61.8.0

- charts/web-ui/Chart.yaml
- charts/web-ui/templates/deployment.yaml
- charts/web-ui/values.yaml
https://github.com/CHORUS-TRE/chorus-web-ui/blob/main/Dockerfile#L29
> fix(charts): web-ui is exposed on port 3000

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
> fix(charts): bump argo-ci version

- README.md
- deployment/applicationset/applicationset-chorus-qa.yaml
- deployment/project/chorus-qa.yaml
> feat(deployment): chorus-qa applicationset and project

- deployment/applicationset/applicationset-chorus-qa.yaml
Follow up of #118 (already applied)
> fix(deployment): wrong project for chorus-qa appset

- bootstrap.sh
- charts/cert-manager/Chart.lock
- charts/cert-manager/Chart.yaml
- charts/cert-manager/values.yaml
> fix(charts): cert-manager to manage its CRDs

- charts/argo-workflows/Chart.lock
- charts/argo-workflows/Chart.yaml
- charts/argo-workflows/values.yaml
Making the CRDs management explicit.
Signed-off-by: Yoan Blanc <yoan.blanc@chuv.ch>
> chore(charts): bump argo-workflows to 0.42

- charts/prometheus-operator-crds/Chart.lock
- charts/prometheus-operator-crds/Chart.yaml
Bump the prometheus-operator to v0.76.0
> chore(charts): bump prometheus-operator-crds to 14.0.0

- charts/self-signed-ca/.helmignore
- charts/self-signed-ca/Chart.yaml
- charts/self-signed-ca/README.md
- charts/self-signed-ca/dev.yaml
- charts/self-signed-ca/templates/_helpers.tpl
- charts/self-signed-ca/templates/ca-certificate.yaml
- charts/self-signed-ca/templates/cluster-issuer.yaml
- charts/self-signed-ca/templates/cluster-issuers.yaml
- charts/self-signed-ca/templates/issuer.yaml
- charts/self-signed-ca/templates/issuers.yaml
- charts/self-signed-ca/values.yaml
https://cert-manager.io/docs/configuration/selfsigned/ into a Helm chart
will help with DSDIP-505
> feat(charts): self-signed CA

- .github/CODEOWNERS
@CHORUS-TRE/bdsc please complain if need be
> fix(ci): Nath is on holidays

- charts/keycloak/Chart.yaml
- charts/keycloak/README.md
- charts/keycloak/templates/certificate.yaml
- charts/keycloak/values.yaml
Used there: https://keycloak.build.chorus-tre.ch/
> fix(charts): Keycloak with certificate

- charts/web-ui/Chart.yaml
- charts/web-ui/values.yaml
> chore(charts): bump web-ui to 0.1.1-alpha

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-web-ui-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
So we can use them in the other chart
> fix(charts): Argo CI to build chorus-web-ui tags

- charts/web-ui/Chart.yaml
- charts/web-ui/templates/deployment.yaml
- charts/web-ui/values.yaml
> fix(charts): web-ui will need some env to run

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/templates/alertmanager-config.yaml
> fix(charts): kube-prometheus-stack not sending alerts

- charts/web-ui/Chart.yaml
- charts/web-ui/templates/deployment.yaml
Fixes:  ⨯ Failed to write image to cache Error: EACCES: permission denied, mkdir '/app/.next/cache'
Signed-off-by: Yoan Blanc <yoan.blanc@chuv.ch>
> fix(charts): add web-ui cache directory

- charts/harbor/values.yaml
No need to bump anything here.
> fix(charts): duplicate key

- charts/cluster-secret/Chart.lock
- charts/cluster-secret/Chart.yaml
- charts/cluster-secret/values.yaml
An easy way to replicate the regcred of the registry in the namespaces of the workspaces
> feat(charts): add cluster-secret

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
- charts/argo-ci/templates/build-web-ui-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
- charts/argo-ci/templates/workflow-template-docker-build.yaml
Will allow to reuse it across the various sensors, hopefully.
> feat(charts): argo-ci with template for docker

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-images-sensor.yaml
For building the zenodo image, @paghiringhelli will commit the Dockerfile
> feat(ci): allow building images for services, namely zenodo

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
> feat(charts): Argo CI to notify on commit statuses

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
- charts/argo-ci/values.yaml
Put the backend into the chorus OCI repository
> feat(charts): build backend image into chorus repo

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-web-ui-sensor.yaml
> feat(charts): run some CI on chorus-web-ui

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
- charts/argo-ci/templates/build-web-ui-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
- charts/argo-ci/templates/workflow-template-github-notify.yaml
:rocket:
With Argo Workflows 3.6, we'll get Markdown in there.
> feat(charts): Argo CI to run tests on chorus-backend

- charts/valkey/Chart.yaml
- charts/valkey/values.yaml
https://github.com/bitnami/charts/blob/main/bitnami/valkey/README.md#host-kernel-settings
> fix(charts): increase somaxconn on Valkey

- charts/valkey/Chart.yaml
- charts/valkey/values.yaml
> Warning  SysctlForbidden  1s    kubelet            forbidden sysctl: "net.core.somaxconn" not allowlisted
> fix(charts): unbork Valkey

- .github/workflows/release.yml
- deployment/applicationset/applicationset-chorus-build.yaml
- deployment/applicationset/applicationset-chorus-dev.yaml
> feat(ci): push new charts to Harbor only

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
- charts/argo-ci/templates/build-web-ui-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
- charts/argo-ci/templates/workflow-template-docker-build.yaml
- charts/argo-ci/values.yaml
Helm charts will have to adapt accordingly
> feat(argo-ci): push images to Harbor

- .github/workflows/release.yml
Fixes https://github.com/CHORUS-TRE/chorus-tre/actions/runs/11476548080/job/31936788634 hopefully
> fix(ci): helm-oci-releaser uses double quotes

- deployment/applicationset/applicationset-chorus-qa.yaml
- deployment/applicationset/applicationset-chorus-sck.yaml
- deployment/applicationset/applicationset-chorus-tds.yaml
- deployment/applicationset/template-applicationset-chorus.yaml
Working on build and dev already
> feat(deploy): use Charts from harbor

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
- charts/argo-ci/templates/build-web-ui-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator.yaml
- charts/argo-ci/templates/workflow-template-docker-build.yaml
- charts/argo-ci/templates/workflow-template-helm-charts-publish.yaml
Refactoring to simplify and make those bits re-usable across the board.
> fix(charts): refactor helm publish as template

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Taking sane defaults from @floriansipp's https://github.com/CHORUS-TRE/environments/pull/250
> feat(charts): enable Grafana

- charts/cluster-secret/Chart.yaml
- charts/cluster-secret/templates/cluster-secret.yaml
- charts/cluster-secret/values.yaml
Hopefully, the CRDs are installed before the resource wants to be created.
> feat(charts): put cluster-secret next to the operator

- .github/workflows/helm-checks.yml
Saving some CPU cycles, hopefully.
> chore(ci): cancel in-progress checks

- charts/didata/Chart.yaml
- charts/didata/values.yaml
> fix(charts): pull DiData from Harbor

- bootstrap.md
- bootstrap.sh
IMHO sealed-secrets should be removed, but I've stopped before that step :D
This works on a bare Colima setup, at least on my machine.
> fix(build): bootstrap with harbor

- bootstrap.sh
- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
- charts/argo-ci/templates/build-workbench-operator-sensor.yaml
Will ease the small bumps done by renovate on the repos, e.g. https://github.com/CHORUS-TRE/workbench-operator/pull/42
> chore(charts): bump Go to 1.23 in CI

- bootstrap.md
- bootstrap.sh
- keycloak.md
Put Keycloak into the bootstrap
> chore(bootstrap): add Keycloak

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/build-chorus-backend-sensor.yaml
See https://github.com/CHORUS-TRE/chorus-backend/pull/23
> feat(charts): argo-ci to test forks

- keycloak.md
The whole Keycloak story, feel free to comment as I'm completing it
> feat(docs): Keycloak setup

- charts/argo-ci/Chart.yaml
- charts/argo-ci/templates/docker-build-template.yaml
Attention, this might break the CI until properly tested.
> feat(argo-ci): user docker cache when building on the CI

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
- add trivy job
- update prometheus chart tag
> feat(charts): add trivy job to prometheus

- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/values.yaml
Reverts CHORUS-TRE/chorus-tre#370
> Revert "feat(charts): add trivy job to prometheus"
